
project_id = "rnctzmgmoopmfohdypcb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[api.serve]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true
