
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

const SUPABASE_URL = "https://rnctzmgmoopmfohdypcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuY3R6bWdtb29wbWZvaGR5cGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTA1ODUsImV4cCI6MjA2Mjk4NjU4NX0.SjE2N2rE5um3qMp_bq2XVSSdKjQFpzccuHih0Ulw72c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
